# Generated by Django 3.0.7 on 2020-11-21 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=300)),
                ('gender', models.CharField(choices=[('MA', 'Male'), ('FE', 'Female'), ('OT', 'Others'), ('NO', 'I do not wish to disclose')], default='NOTDISCLOSE', max_length=2)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, max_length=1000)),
                ('mental_illness', models.CharField(default='Not diagnosed yet', max_length=400)),
                ('therapist', models.ManyToManyField(blank=True, null=True, related_name='patients', to='accounts.Therapist')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='accounts.Profile')),
            ],
        ),
    ]
