# Generated by Django 3.0.7 on 2020-11-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('therapist_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patients',
            options={'verbose_name_plural': 'Patients'},
        ),
        migrations.AlterField(
            model_name='patients',
            name='therapist',
            field=models.ManyToManyField(blank=True, related_name='patients', to='accounts.Therapist'),
        ),
    ]
