# Generated by Django 3.0.7 on 2021-01-12 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapist_dashboard', '0002_auto_20201125_1756'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patients',
        ),
    ]
