# Generated by Django 3.0.7 on 2020-11-18 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('community_forum', '0002_auto_20201118_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerVotes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('up_votes', models.IntegerField(blank=True)),
                ('down_votes', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionVotes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('up_votes', models.IntegerField(blank=True)),
                ('down_votes', models.IntegerField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='answers',
            name='votes',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='votes',
        ),
        migrations.DeleteModel(
            name='Votes',
        ),
        migrations.AddField(
            model_name='questionvotes',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionvotes', to='community_forum.Questions'),
        ),
        migrations.AddField(
            model_name='questionvotes',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionvotes', to='accounts.Profile'),
        ),
        migrations.AddField(
            model_name='answervotes',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answervotes', to='community_forum.Answers'),
        ),
        migrations.AddField(
            model_name='answervotes',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answervotes', to='accounts.Profile'),
        ),
    ]
