# Generated by Django 3.0.7 on 2020-11-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('community_forum', '0004_auto_20201121_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='votes',
            field=models.ManyToManyField(related_name='questions_votes', to='accounts.Profile'),
        ),
    ]
