# Generated by Django 3.0.7 on 2020-11-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('community_forum', '0005_questions_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionvotes',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questionvotes',
            name='user',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='votes',
        ),
        migrations.AddField(
            model_name='questions',
            name='down_votes',
            field=models.ManyToManyField(related_name='questions_down_votes', to='accounts.Profile'),
        ),
        migrations.AddField(
            model_name='questions',
            name='up_votes',
            field=models.ManyToManyField(related_name='questions_up_votes', to='accounts.Profile'),
        ),
        migrations.DeleteModel(
            name='AnswerVotes',
        ),
        migrations.DeleteModel(
            name='QuestionVotes',
        ),
    ]
