# Generated by Django 3.0.7 on 2020-11-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('community_forum', '0006_auto_20201125_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='down_votes',
            field=models.ManyToManyField(related_name='answers_down_votes', to='accounts.Profile'),
        ),
        migrations.AddField(
            model_name='answers',
            name='up_votes',
            field=models.ManyToManyField(related_name='answers_up_votes', to='accounts.Profile'),
        ),
    ]
