# Generated by Django 3.0.7 on 2020-11-25 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community_forum', '0007_auto_20201125_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='answer',
        ),
    ]
