# Generated by Django 3.0.7 on 2020-11-18 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ask_the_doctor', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_to_therapist',
            name='therapist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionfortherapist', to='accounts.Therapist'),
        ),
        migrations.AddField(
            model_name='question_to_therapist',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionfortherapist', to='accounts.Profile'),
        ),
        migrations.AddField(
            model_name='answers_from_therapist',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answersfromtherapist', to='Ask_the_doctor.question_to_therapist'),
        ),
        migrations.AddField(
            model_name='answers_from_therapist',
            name='therapist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answersfromtherapist', to='accounts.Therapist'),
        ),
        migrations.AddField(
            model_name='answers_from_therapist',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answersfromtherapist', to='accounts.Profile'),
        ),
    ]
