# Generated by Django 3.0.7 on 2020-12-14 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('private_chats', '0002_auto_20201214_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalMessages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('message', models.TextField(max_length=2000)),
                ('msg_sent_time', models.DateTimeField(auto_now_add=True)),
                ('chatroom', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_messages', to='private_chats.PersonalChatroom')),
            ],
            options={
                'verbose_name_plural': 'Personal messages',
            },
        ),
    ]
