# Generated by Django 3.0.7 on 2020-12-31 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('private_chats', '0004_auto_20201221_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchatroom',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='groupchatroom', to='accounts.Profile'),
        ),
    ]
