# Generated by Django 3.0.7 on 2020-12-31 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('private_chats', '0005_groupchatroom_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchatroom',
            name='members',
            field=models.ManyToManyField(related_name='group_members', to='accounts.Profile'),
        ),
    ]
