# Generated by Django 3.0.7 on 2021-01-02 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('private_chats', '0007_auto_20210101_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChatroom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=25)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='groupchatroom', to='accounts.Profile')),
                ('members', models.ManyToManyField(related_name='group_members', to='accounts.Profile')),
            ],
            options={
                'verbose_name_plural': 'Group chatroom',
            },
        ),
        migrations.CreateModel(
            name='PersonalChatroom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('msg_receiver', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='msg_receiver', to='accounts.Profile')),
                ('msg_sender', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='msg_sender', to='accounts.Profile')),
            ],
            options={
                'verbose_name_plural': 'Personal Chatroom',
            },
        ),
        migrations.CreateModel(
            name='PersonalMessages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('message', models.TextField(max_length=2000)),
                ('msg_sent_time', models.DateTimeField(auto_now_add=True)),
                ('chatroom', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_messages', to='private_chats.PersonalChatroom')),
            ],
            options={
                'verbose_name_plural': 'Personal messages',
            },
        ),
        migrations.CreateModel(
            name='GroupMessages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('msg_sent_time', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(blank=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupchat', to='private_chats.GroupChatroom')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='groupchatuser', to='accounts.Profile')),
            ],
            options={
                'verbose_name_plural': 'Group messages',
            },
        ),
    ]
