# Generated by Django 3.0.7 on 2021-01-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('private_chats', '0009_auto_20210102_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupchatroom',
            name='members',
        ),
        migrations.RemoveField(
            model_name='groupchatroom',
            name='name',
        ),
        migrations.RemoveField(
            model_name='groupmessages',
            name='room',
        ),
        migrations.AddField(
            model_name='groupmessages',
            name='members',
            field=models.ManyToManyField(related_name='group_members', to='accounts.Profile'),
        ),
    ]
