# Generated by Django 3.0.7 on 2021-01-03 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('private_chats', '0010_auto_20210103_1122'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupChatroom',
        ),
    ]
